export enum VIDEO_PLAYER_MODE {
  ROUNDED_LEFT = "ROUNDED_LEFT",
  ROUNDED_RIGHT = "ROUNDED_RIGHT",
  ROUNDED_R_NONE = "ROUNDED_R_NONE",
}
export enum ORIENTATION {
  HORIZONTAL = "HORIZONTAL",
  VERTICAL = "VERTICAL",
}
